---
kind: PersistentVolume
apiVersion: v1
metadata:
  labels:
    type: ${STORAGE_CLASS}
  name: redis-data-pv
  namespace: cowbull
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: ${STORAGE_CLASS}
  local:
    path: "${DIRECTORY}"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
         - key: kubernetes.io/hostname
           operator: In
           values: 
           - "vm-djs-k8s-worker-1-eus-${random_num}"
           - "vm-djs-k8s-worker-2-eus-${random_num}"
      # - matchExpressions:
      #    - key: node-role.kubernetes.io/master
      #      operator: DoesNotExist
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: cowbull
  name: redis-data-pvc
  namespace: cowbull
spec:
  storageClassName: ${STORAGE_CLASS}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
