---
kind: PersistentVolume
apiVersion: v1
metadata:
  labels:
    type: ${STORAGE_CLASS}
  name: redis-data-pv
  namespace: cowbull
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: ${STORAGE_CLASS}
  local:
    path: "${STORAGE}"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: role
          operator: In
          values:
          - "worker"
  persistentVolumeReclaimPolicy: Retain
